# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Brett_2\Desktop\Dev\minecop.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(837, 826)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.serverLabel = QtWidgets.QLabel(self.centralwidget)
        self.serverLabel.setObjectName("serverLabel")
        self.horizontalLayout_4.addWidget(self.serverLabel)
        self.settingButt = QtWidgets.QPushButton(self.centralwidget)
        self.settingButt.setObjectName("settingButt")
        self.horizontalLayout_4.addWidget(self.settingButt)
        self.serverButt = QtWidgets.QPushButton(self.centralwidget)
        self.serverButt.setObjectName("serverButt")
        self.horizontalLayout_4.addWidget(self.serverButt)
        self.logButt = QtWidgets.QPushButton(self.centralwidget)
        self.logButt.setObjectName("logButt")
        self.horizontalLayout_4.addWidget(self.logButt)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.serverNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.serverNameLabel.setObjectName("serverNameLabel")
        self.verticalLayout.addWidget(self.serverNameLabel)
        self.fileLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileLabel.setObjectName("fileLabel")
        self.verticalLayout.addWidget(self.fileLabel)
        self.fileList = QtWidgets.QListWidget(self.centralwidget)
        self.fileList.setMaximumSize(QtCore.QSize(120000, 16777215))
        self.fileList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.fileList.setObjectName("fileList")
        self.verticalLayout.addWidget(self.fileList)
        self.playerLabel = QtWidgets.QLabel(self.centralwidget)
        self.playerLabel.setObjectName("playerLabel")
        self.verticalLayout.addWidget(self.playerLabel)
        self.playerList = QtWidgets.QListWidget(self.centralwidget)
        self.playerList.setObjectName("playerList")
        self.verticalLayout.addWidget(self.playerList)
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.verticalLayout.addWidget(self.refreshButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.locationLabel = QtWidgets.QLabel(self.centralwidget)
        self.locationLabel.setObjectName("locationLabel")
        self.horizontalLayout.addWidget(self.locationLabel)
        self.locBox = QtWidgets.QLineEdit(self.centralwidget)
        self.locBox.setObjectName("locBox")
        self.horizontalLayout.addWidget(self.locBox)
        self.saveLocationButt = QtWidgets.QPushButton(self.centralwidget)
        self.saveLocationButt.setObjectName("saveLocationButt")
        self.horizontalLayout.addWidget(self.saveLocationButt)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.locComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.locComboBox.setObjectName("locComboBox")
        self.verticalLayout_3.addWidget(self.locComboBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filterLabel = QtWidgets.QLabel(self.centralwidget)
        self.filterLabel.setObjectName("filterLabel")
        self.horizontalLayout_2.addWidget(self.filterLabel)
        self.filterBox = QtWidgets.QLineEdit(self.centralwidget)
        self.filterBox.setObjectName("filterBox")
        self.horizontalLayout_2.addWidget(self.filterBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mine Cop"))
        self.serverLabel.setText(_translate("MainWindow", "Server"))
        self.settingButt.setText(_translate("MainWindow", "Settings"))
        self.serverButt.setText(_translate("MainWindow", "Change Server"))
        self.logButt.setText(_translate("MainWindow", "Start Logging"))
        self.serverNameLabel.setText(_translate("MainWindow", "servername"))
        self.fileLabel.setText(_translate("MainWindow", "Log Files"))
        self.playerLabel.setText(_translate("MainWindow", "Players"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.locationLabel.setText(_translate("MainWindow", "Location"))
        self.saveLocationButt.setText(_translate("MainWindow", "Save"))
        self.filterLabel.setText(_translate("MainWindow", "Filter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
